# -*- coding: utf-8 -*-
"""concrete_str.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQ25zvwbQ3oWiESg_51hx77-vWJxG-Sm
"""

#upload concrete+compressive+strength.zip

!unzip -o concrete+compressive+strength.zip

!pip install xlrd

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from scipy import stats

column_names=[
    'Cement',
    'Blast_Furnace_Slag',
    'Fly_Ash',
    'Water',
    'Superplasticizer',
    'Coarse_Aggregate',
    'Fine_Aggregate',
    'Age',
    'Concrete_compressive_strength'
]
df=pd.read_excel('Concrete_Data.xls',names=column_names)
df.head()

"""Plotting Histogram, PDF,and CDF"""

#set plot style
sns.set_style('whitegrid')

#Relating each axis to columns
for col in df.columns:
  fig, ax= plt.subplots(1,3, figsize=(18,5))
  fig.suptitle(f'Distribution analysis fro {col}',fontsize=16)

  #Histogram
  sns.histplot(df[col],ax=ax[0],bins=30, kde=False)
  ax[0].set_xlabel(col)
  ax[0].set_ylabel('Frequency')
  ax[0].set_title('Histogram')

  #Probability density Function
  sns.kdeplot(df[col],ax=ax[1],fill=True)
  ax[1].set_xlabel(col)
  ax[1].set_ylabel('Probability Density')
  ax[1].set_title('Probability Density Function')

  #Cumulative Density Function
  #Sort data and calculate cumulative probab
  sorted_data=np.sort(df[col])
  cum_prob=np.arange(1,len(sorted_data)+1)/len(sorted_data)
  ax[2].plot(sorted_data,cum_prob,color='red')
  ax[2].set_xlabel(col)
  ax[2].set_ylabel('Cumulative Probability')
  ax[2].set_title('Cumulative Density Function')

  plt.tight_layout()
  plt.show()

"""a) Compute and comment on their statistical parameters (mean, variance, skewness, kurtosis).

"""

#Calculating stats
stats_df=pd.DataFrame({
    'Mean':df.mean(),
    'Variance':df.var(),
    'Standard Deviation':df.std(),
    'Skewness':df.skew(),
    'Kurtosis':df.kurtosis()
    #Normal Kurtiosis=0
})
stats_df

#Calculate correlation matrix
corr_matrix=df.corr()

#plot the heatmap
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix,annot=True,cmap='coolwarm',linewidths=0.5)
plt.title('Correlation Matrix of concrete ingredients and strength')
plt.show()

""" Estimate the statistical parameters of compressive strength (mean, variance, standard deviation) and report them along with their 95% confidence intervals."""

strength=df['Concrete_compressive_strength']

strength_mean=strength.mean()
strength_var=strength.var()
strength_std=strength.std()

print(f'Mean: {strength_mean}')
print(f'Variance: {strength_var}')
print(f'Standard Deviation: {strength_std}')

#calculating 95% CI
#We are using t-distrubition as population std is unknown, chi dist fro variance
n=len(strength)
ci_mean=stats.t.interval(0.95,n-1,loc=strength_mean,scale=stats.sem(strength))
ci_var=stats.chi2.interval(0.95,n-1,loc=strength_var,scale=stats.sem(strength)**2)
ci_std=stats.t.interval(0.95,n-1,loc=strength_std,scale=stats.sem(strength))

print(f"Analysis for Concrete Compressive Strength:")
print(f"---------------------------------------------")
print(f"Mean: {strength_mean:.2f} MPa")
print(f"Variance: {strength_var:.2f} MPa^2")
print(f"Standard Deviation: {strength_std:.2f} MPa")
print(f"95% Confidence Interval for the Mean: ({ci_mean[0]:.2f} MPa, {ci_mean[1]:.2f} MPa)")
print(f"95% Confidence Interval for the Variance: ({ci_var[0]:.2f} MPa^2, {ci_var[1]:.2f} MPa^2)")
print(f"95% Confidence Interval for the Standard Deviation: ({ci_std[0]:.2f} MPa, {ci_std[1]:.2f} MPa)")

"""For compressive strength, test whether the data follows a normal distribution using:
Probability plots (Q–Q plots)
Normality tests (e.g: Kolmogorov–Smirnov)
Comment on whether compressive strength data can reasonably be modeled as a normal distribution.
"""

#1.Probability Plots(Q-Q)
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
stats.probplot(strength,dist='norm',plot=plt)
plt.title('Q-Q Plot fro compressive strength')
plt.xlabel('Theoretical Quantiles')
plt.ylabel('Sample Quantiles')

# Add a histogram with a normal curve overlay for visual comparison
plt.subplot(1,2,2)
sns.histplot(strength,kde=True,bins=30, stat='density')
plt.title('Histogram fro compressive strength')
plt.xlabel('Compressive Strength')
plt.ylabel('Density')

#Plot a perfect normal distribution over it
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = stats.norm.pdf(x, strength_mean, strength_std)
plt.plot(x, p, 'k', linewidth=2)
title = "Fit results: mu = %.2f,  std = %.2f" % (strength_mean, strength_std)
plt.title(title)

plt.tight_layout()
plt.show()

ks_stat, ks_p = stats.kstest(strength, 'norm', args=(strength.mean(), strength.std()))
print(f"\nKolmogorov-Smirnov Test:")
print(f"Statistic: {ks_stat:.4f}, p-value: {ks_p:.4f}")

import statsmodels.api as sm
from sklearn.metrics import mean_squared_error

# --- a) Perform a regression analysis ---

# 1. Define predictor (X) and target (y) variables
# The problem is a regression problem with 8 input variables and 1 output variable [cite: 7]
X = df.drop('Concrete_compressive_strength', axis=1)
y = df['Concrete_compressive_strength']

# 2. Add a constant (intercept) to the predictor variables for the statsmodels library
X = sm.add_constant(X)

# 3. Fit the Ordinary Least Squares (OLS) linear regression model
model = sm.OLS(y, X)
results = model.fit()

# 4. Print the detailed summary of the regression results
print("\n--- Regression Analysis Results ---")
print(results.summary())